version: '3.4'
services:
  database:
    container_name: exampleDb
    image: postgres
    environment:
      POSTGRES_DB: exampleDatabase
      POSTGRES_USER: exampleUser
      POSTGRES_PASSWORD: examplePassword
    volumes:
      - ./support:/docker-entrypoint-initdb.d
    ports:
      - 54321:5432
